context:
  version: "3.8.1"

package:
  name: minicover
  version: ${{ version }}

source:
  url: https://github.com/lucaslorentz/minicover/archive/v${{ version }}.tar.gz
  sha256: 48ede1f32cc08c9b946fd1a28aba439cd74f31c76248e816544efe670a2efdea

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - minicover --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cross platform code coverage tool for .NET Core
  homepage: https://github.com/lucaslorentz/minicover
  repository: https://github.com/lucaslorentz/minicover

extra:
  recipe-maintainers:
    - danielnachun
