context:
  version: "3.10.0"

package:
  name: minicover
  version: ${{ version }}

source:
  url: https://github.com/lucaslorentz/minicover/archive/v${{ version }}.tar.gz
  sha256: d9b38f70d1b1fcdbe8f2d8c874fafa740894869aa0d123976e288fec60f4d7bc

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - minicover --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cross platform code coverage tool for .NET Core
  homepage: https://github.com/lucaslorentz/minicover
  repository: https://github.com/lucaslorentz/minicover

extra:
  recipe-maintainers:
    - danielnachun
